M48
; DRILL file {KiCad 7.0.5} date Wed Jul 12 14:46:15 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-07-12T14:46:15+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.900
%
G90
G05
T1
X99.78Y-54.105
X99.78Y-59.885
T2
X95.72Y-72.32
X97.52Y-72.32
T3
X96.632Y-64.332
X96.632Y-67.332
T0
M30
